buffs:
- /effect <plr> 15 9999 1 true
- /effect <plr> 16 9999 1 true
- /effect <plr> 5 9999 5 true
- /give <plr> minecraft:iron_bars 2 16:10 name:&6Wildmutt's_Claws
- /mgive <plr> trackingwand
class: wildmutt
costumes:
- chatcolor: '&6'
  name: §6W§ei§6ldm§2u§6tt
  sig: iIO4qURoinag+HRasHZh4AuwjQUYk0tn72gSeBrKJqGoDNcfGBcheLsq1IOv/5xWnaAqC3yMRDJNZfyFIgoV35H+Ol0Yus5abJHuD7raswjjLbROBZPvfbkt784QHsrStg3i4o1MrOGd+6lXlwqfiJWQQmbZ4KPHH5Gp8YjzlFTA/RliehkeEP+6UxAqLaSxHUmM+/JxA2mPk3JDnTiarg3DB2rjWmUxuHSIzV36z+q9krD9Ye3l603knwkqTd+sLAGR5jugXxRCae1Hdzlqg1Sd+hqUU0o+95gnSds6W5brEc4Wh6dIl4dwC2FerCvJ3SqewJekHmqeey7LNv6YiEIB34cDI1vR+tCrEIqdv/6yry4r8Ovy7BERDGawYw6AWf1cL2JOcW552M8BK0GWQWU0TXitDfPCVmTCtJM8Z2TIRwyT0GWY9A02MC4rReZG/O9d2gBWeBhQh2tuyVR8PYfcZaa5vLjE5pc4mhVg5r5zkv6kXN9vR7AsDPruMVPaFGY+Z5wWEaJv49iwqlXjBiMbblq9PzfBuSOxEE04dsmLMhzdnHkUo8POBiYFgrdAcR6Y4exF/516HkxjGuBVjrxIwbXUJercINCBMg6wvbL88XJ+E9SoSLG7/H6kleD3ur+wYz+1Cpx3NukiOGlzqr8OwASE6AX2mouZLIFt540=
  val: eyJ0aW1lc3RhbXAiOjE1MTU4NzA1Mzc1MzgsInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2VjMTRmOTY3MjQ5OTBjMzVkNGZiNmMyOWVjNDdiNzU3NDlmNmIzNjlkYzA0NjFhNTEzNTcwMTE2M2Q5YjQifX19
jump: 2
maxHearts: 30
permissions:
  superherocity:
  - powers.herotransform
powers:
- /buff
- /jump <0-2>
- /run <0-4>
- /cast tracking
- /herotransform
run: 4
speech: RRRAAWWRRRRR
trail: [
  ]
transformations:
- ben10
- alienx
- heatblast
- lodestar
- goop
- fourarms
- xlr8
- diamondhead
- ghostfreak
- upgrade
